// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'please run `flutterfire configure`',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIevMUSfPIDCLBkhKyaTBsG2DVuWLatFE',
    appId: '1:642695919798:web:2e44ef37e9e686f229ce17',
    messagingSenderId: '642695919798',
    projectId: 'fintrack-5fe9d',
    authDomain: 'fintrack-5fe9d.firebaseapp.com',
    storageBucket: 'fintrack-5fe9d.firebasestorage.app',
    measurementId: 'G-TL8DX72VPZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtCxbZEk79wXLuYcShkbOK5kHf6eWZ1nY',
    appId: '1:642695919798:ios:2242a820c3ce3d4529ce17',
    messagingSenderId: '642695919798',
    projectId: 'fintrack-5fe9d',
    storageBucket: 'fintrack-5fe9d.firebasestorage.app',
    androidClientId: '642695919798-6ve7grq2bb1obsdsd4g95qf42ferrfq4.apps.googleusercontent.com',
    iosClientId: '642695919798-8ord6qg2r7jbps9oc073b5v9eos3ue1q.apps.googleusercontent.com',
    iosBundleId: 'com.fintrack.fintrack',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCxbZEk79wXLuYcShkbOK5kHf6eWZ1nY',
    appId: '1:642695919798:ios:c2cae3d006ee364529ce17',
    messagingSenderId: '642695919798',
    projectId: 'fintrack-5fe9d',
    storageBucket: 'fintrack-5fe9d.firebasestorage.app',
    androidClientId: '642695919798-6ve7grq2bb1obsdsd4g95qf42ferrfq4.apps.googleusercontent.com',
    iosClientId: '642695919798-uferp615dm7ulnptng2r80birnvcrg0n.apps.googleusercontent.com',
    iosBundleId: 'com.macvonimesh.fintrack',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZqh1SzDtUHZvMBw7OfrFSRnYk4WD6fQ',
    appId: '1:642695919798:android:cc70c18d83487e7529ce17',
    messagingSenderId: '642695919798',
    projectId: 'fintrack-5fe9d',
    storageBucket: 'fintrack-5fe9d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIevMUSfPIDCLBkhKyaTBsG2DVuWLatFE',
    appId: '1:642695919798:web:3db7721e1638763f29ce17',
    messagingSenderId: '642695919798',
    projectId: 'fintrack-5fe9d',
    authDomain: 'fintrack-5fe9d.firebaseapp.com',
    storageBucket: 'fintrack-5fe9d.firebasestorage.app',
    measurementId: 'G-6Y341NJVY9',
  );

}